export default {
    CHANGE_AREA_LIST : "AreaEvent.CHANGE_AREA_LIST",
    CHANGE_SIGUNDO_DATA : "AreaEvent.CHANGE_SIGUNDO_DATA",

    TOGGLE_SEARCH_FORM: "TOGGLE_SEARCH_FORM",

    UPDATE_PAGE_NO  : "UPDATE_PAGE_NO",
    UPDATE_AREA_CODE : "UPDATE_AREA_CODE",
    UPDATE_SIGUNGU_CODE : "UPDATE_SIGUNGU_CODE",
    UPDATE_SEARCH_CONTENT_ID : "UPDATE_SEARCH_CONTENT_ID",

    FETCH_AREAS         : "AreaEvent.FETCH_AREAS",
    FETCH_AREAS_SUCCESS : "AreaEvent.FETCH_AREAS_SUCCESS",
    FETCH_AREAS_FAILURE : "AreaEvent.FETCH_AREAS_FAILURE",

    FETCH_SIGUNDOS : "FETCH_SIGUNDOS",
    FETCH_SIGUNDOS_SUCCESS : "FETCH_SIGUNDOS_SUCCESS",
    FETCH_SIGUNDOS_FAILURE : "FETCH_SIGUNDOS_FAILURE",

    FETCH_TOUR_LIST : "FETCH_TOUR_LIST",
    FETCH_TOUR_LIST_SUCCESS : "FETCH_TOUR_LIST_SUCCESS",
    FETCH_TOUR_LIST_FAILURE : "FETCH_TOUR_LIST_FAILURE",

    FETCH_TOUR_ITEM_DETAIL_SUCCESS:"FETCH_TOUR_ITEM_DETAIL_SUCCESS",
    FETCH_TOUR_ITEM_DETAIL_FAILURE:"FETCH_TOUR_ITEM_DETAIL_FAILURE"

}
